services:
  app:
    build: .
    container_name: library-api
    ports:
      - "3000:3000"
    env_file:
      - .env
    depends_on:
      db:
          condition: service_healthy
    command: sh -c "npx node-pg-migrate up && npm start"
    volumes:
      - .:/usr/src/app:delegated
      - /usr/src/app/node_modules
      - /usr/src/app/dist
  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: librarian
      POSTGRES_PASSWORD: lib123!
      POSTGRES_DB: libra
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -d libra -U librarian"]
      interval: 10s
      timeout: 10s
      retries: 5

volumes:
  db_data:
